# Generated by Django 5.0.7 on 2024-08-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('metal', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('assay', models.CharField(max_length=100)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('circulation', models.CharField(max_length=100)),
                ('mint', models.CharField(max_length=100)),
                ('minting_from', models.DateField()),
                ('minting_to', models.DateField()),
                ('denomination', models.CharField(max_length=50)),
            ],
        ),
    ]
