# Generated by Django 5.0.7 on 2024-08-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_base', '0002_remove_coin_minting_from_remove_coin_minting_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='diameter',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
