# Generated by Django 5.0.7 on 2024-08-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin_base', '0003_coin_diameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='coin_image',
            field=models.ImageField(default='', upload_to='coin_images'),
            preserve_default=False,
        ),
    ]
